spring.application:
  name: sns

spring:
  data:
      redis:
        url: redis://:pe7fd2cb62ff05b4142b11df01c680d91dbe82a3084a5e50ab3847a8e394267fc@ec2-34-233-243-60.compute-1.amazonaws.com:23169
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ceu9lmqblp8t3q.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d5v5tj8elnqa7j
    username: un6ujhfu1osnp
    password: p47b5cb2f9ba7699de3f41cc6c046c7277d39dc5fb5fe3072ab706927f89b2b1a
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always

jwt:
  secret-key: fast_campus.sns-application-2024.secret_key
  # 30 days
  token.expired-time-ms: 2592000000